name: Test mkdocs build
on: push

jobs:
  build:
    name: test build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: build
        run: |
          sudo apt-get install plantuml git curl python3 python3-pip default-jre graphviz
          wget https://bootstrap.pypa.io/get-pip.py
          python get-pip.py
          pip install -r requirements.txt
          chmod +x resolve_remote.sh
          ./resolve_remote.sh ${{secrets.DEPLOY_TOKEN}}
          mkdocs build --strict

